version: 2

sources:
  - name: TRIPLEPEAK_SB
    schema: public
    tables:
      - name: TRIPLEPEAK_SPINS_LP
      - name: RF_SPINS_CUSTOMATRRIBUTES

models:
  - name: sb_triplepeak_spins_lp
    description: "SB TriplePeak Spins LP"
    columns:
      - name: "PRODUCT LEVEL"
        description: "Product Level"
      - name: "CATEGORY"
        description: "Category"
      - name: "SUBCATEGORY"
        description: "Subcategory"
      - name: "CHANNEL/OUTLET"
        description: "Channel/Outlet"
      - name: "BRAN" 
        description: "Brand" 
      - name: "PRODUCT UNIVERSE"
        description: "Product Universe"
      - name: "UPC"
        description: "UPC"
      - name: "PRODUCT DESCRIPTION"
        description: "Description"
      - name: "TIME PERIOD"
        description: "Time Period"
      - name: "Time Period End Date"
        description: "Time Period End Date"
        
      - name: "Geography"
        description: "Geography"
      - name: "POSITIONING GROUP"
        description: "POSITIONING GROUP"
      - name: "PRODUCT TYPE"
        description: "PRODUCT TYPE"
      - name:  "Department"
        description:  "Department"
      - name: "STORAGE"
        description: "STORAGE"
      - name: "DIET - KETO DIET"
        description: "DIET - KETO DIET"
      - name: "DIET - PALEO DIET"
        description: "DIET - PALEO DIET"
      - name: "FLAVOR"
        description: "FLAVOR"
        
      - name: "LABELED NON-GMO"
        description: "LABELED NON-GMO"
      - name: "LABELED GRASS FED"
        description: "LABELED GRASS FED"
      - name: "LABELED ORGANIC"
        description: "LABELED ORGANIC"
      - name: "LABELED NITRATE FREE"
        description: "LABELED NITRATE FREE"
      - name: "PLANT BASED"
        description: "PLANT BASED"
      - name: "ANIMAL TYPE"
        description: "ANIMAL TYPE"
      - name: "PALEO"
        description: "PALEO"
      - name: "UNIT OF MEASURE"
        description: "UNIT OF MEASURE"
      - name: "$ sales"
        description: "$ sales ya" 
      - name: "$ sales ya"
        description: "$ sales ya"
      - name: "no of stores selling"
        description: "no of stores selling" 
      - name: "number of weeks selling"
        description: "number of weeks selling" 
      - name: tdp
        description: "TDP" 
        
metrics:
  - name: "$ sales % chg ya"
    label: "$ sales % change Ya"
    model: ref('sb_triplepeak_spins_lp')
    description: "Sales percentage change from year ago"

    type: ROUND
    sql:  case when SUM("$ sales ya")=0 then 0 else  ((SUM("$ sales") /SUM("$ sales ya"))-1)*100 end 

    timestamp: "Time Period End Date"
    time_grains: [day, week, month]

    dimensions:
      - "Product Level"
      - "Category" 
      - "Subcategory"
      - "Channel/Outlet"
      - "Brand"
      - "Product Universe"
      - "UPC"
      - "Description"
      - "Time Period"
      - "Geography"
      - "POSITIONING GROUP"
      - "PRODUCT TYPE"
      - "Department"
      - "STORAGE"
      - "UNIT OF MEASURE"
      - "PLANT BASED"

      
  
  - name: "$/S/W"
    label: "$ sales/ store selling / weeks selling"
    model: ref('sb_triplepeak_spins_lp')
    description: "$ sales/ store selling / weeks selling"

    type: ROUND
    sql:  case when max("no of stores selling")=0 or max("number of weeks selling")=0 then 0 else  (SUM("$ sales") /max("no of stores selling")/max("number of weeks selling")) end 

    timestamp: "Time Period End Date"
    time_grains: [day, week, month]

    dimensions:
      - "Product Level"
      - "Category" 
      - "Subcategory"
      - "Channel/Outlet"
      - "Brand"
      - "Product Universe"
      - "UPC"
      - "Description"
      - "Time Period"
      - "Geography"
      - "POSITIONING GROUP"
      - "PRODUCT TYPE"
      - "Department"
      - "STORAGE"
      - "UNIT OF MEASURE"
      - "PLANT BASED"

  - name: "$/TDP"
    label: "$/TDP"
    model: ref('sb_triplepeak_spins_lp')
    description: "$/TDP"

    type: ROUND
    sql:  case when SUM(tdp)=0 then 0 else  SUM("$ sales")/SUM(tdp) end 

    timestamp: "Time Period End Date"
    time_grains: [day, week, month]

    dimensions:
      - "Product Level"
      - "Category" 
      - "Subcategory"
      - "Channel/Outlet"
      - "Brand"
      - "Product Universe"
      - "UPC"
      - "Description"
      - "Time Period"
      - "Geography"
      - "POSITIONING GROUP"
      - "PRODUCT TYPE"
      - "Department"
      - "STORAGE"
      - "UNIT OF MEASURE"
      - "PLANT BASED"