version: 2

sources:
  - name: TRIPLEPEAK_SB
    schema: public
    tables:
      - name: TRIPLEPEAK_SPINS_LP
      - name: RF_SPINS_CUSTOMATRRIBUTES

models:
  - name: sb_triplepeak_spins_lp
    description: "SB TriplePeak Spins LP"
    columns:
      - name: "PRODUCT LEVEL"
        description: "PRODUCT LEVEL"
      - name: "CATEGORY"
        description: "CATEGORY"
      - name: "SUBCATEGORY"
        description: "SUBCATEGORY"
      - name: "CHANNEL/OUTLET"
        description: "CHANNEL/OUTLET"
      - name: "BRAND" 
        description: "BRAND" 
      - name: "PRODUCT UNIVERSE"
        description: "PRODUCT UNIVERSE"
      - name: "UPC"
        description: "UPC"
      - name: "PRODUCT DESCRIPTION"
        description: "PRODUCT DESCRIPTION"
      - name: "TIME PERIOD"
        description: "TIME PERIOD"
      - name: "TIME PERIOD ABR"
        description: "TIME PERIOD ABREVIATION"
      - name: "TIME PERIOD END DATE"
        description: "TIME PERIOD END DATE"
        
      - name: "GEOGRAPHY"
        description: "GEOGRAPHY"
      - name: "POSITIONING GROUP"
        description: "POSITIONING GROUP"
      - name: "PRODUCT TYPE"
        description: "PRODUCT TYPE"
      - name:  "DEPARTMENT"
        description:  "DEPARTMENT"
      - name: "STORAGE"
        description: "STORAGE"
      - name: "DIET - KETO DIET"
        description: "DIET - KETO DIET"
      - name: "DIET - PALEO DIET"
        description: "DIET - PALEO DIET"
      - name: "FLAVOR"
        description: "FLAVOR"
        
      - name: "LABELED NON-GMO"
        description: "LABELED NON-GMO"
      - name: "LABELED GRASS FED"
        description: "LABELED GRASS FED"
      - name: "LABELED ORGANIC"
        description: "LABELED ORGANIC"
      - name: "LABELED NITRATE FREE"
        description: "LABELED NITRATE FREE"
      - name: "PLANT BASED"
        description: "PLANT BASED"
      - name: "ANIMAL TYPE"
        description: "ANIMAL TYPE"
      - name: "PALEO"
        description: "PALEO"
      - name: "UNIT OF MEASURE"
        description: "UNIT OF MEASURE"
      - name: "$ SALES"
        description: "$ SALES" 
      - name: "$ SALES YA"
        description: "$ SALES YA"
      - name: "NO OF STORES SELLING"
        description: "NO OF STORES SELLING" 
      - name: "NUMBER OF WEEKS SELLING"
        description: "NUMBER OF WEEKS SELLING" 
      - name: "TDP"
        description: "TDP" 
        
metrics:
  - name: "$ SALES % CHG YA"
    label: "$ SALES % CHANGE YA"
    model: ref('sb_triplepeak_spins_lp')
    description: "Sales percentage change from year ago"

    type: ROUND
    sql:  case when SUM("$ SALES YA")=0 then 0 else  ((SUM("$ SALES")/SUM("$ SALES YA"))-1)*100 end 

    timestamp: "TIME PERIOD END DATE"
    time_grains: [day, week, month]

    dimensions:
      - "PRODUCT LEVEL"
      
  - name: "$/S/W"
    label: "$ sales/ store selling / weeks selling"
    model: ref('sb_triplepeak_spins_lp')
    description: "$ sales/ store selling / weeks selling"

    type: ROUND
    sql:  case when max("NO OF STORES SELLING")=0 or max("NUMBER OF WEEKS SELLING")=0 then 0 else  (SUM("$ SALES") /max("NO OF STORES SELLING")/max("NUMBER OF WEEKS SELLING")) end 

    timestamp: "TIME PERIOD END DATE"
    time_grains: [day, week, month]

    dimensions:
      - "PRODUCT LEVEL"
      - "CATEGORY" 
 
  

  - name: "$/TDP"
    label: "$/TDP"
    model: ref('sb_triplepeak_spins_lp')
    description: "$/TDP"

    type: ROUND
    sql:  case when SUM("TDP")=0 then 0 else  SUM("$ SALES")/SUM("TDP") end 

    timestamp: "TIME PERIOD END DATE"
    time_grains: [day, week, month]

    dimensions:
      - "PRODUCT LEVEL"
      - "CATEGORY" 