version: 2

sources:
  - name: TRIPLEPEAK_SB
    schema: public
    tables:
      - name: TRIPLEPEAK_SPINS_LP
      - name: RF_SPINS_CUSTOMATRRIBUTES

models:
  - name: sb_triplepeak_spins_lp
    description: "SB TriplePeak Spins LP"
    columns:
      - name: PRODUCT_LEVEL
        description: "PRODUCT LEVEL"
